import 'material-design-icons-iconfont/dist/material-design-icons.css';
import Vue from 'vue';
import Vuetify, {
  VApp, // required
  VBtn,
  VContainer,
  VContent,
  VFlex,
  VForm,
  VLayout,
  VTextField,
  VTooltip,
  VIcon,
  VToolbar,
  VToolbarTitle,
  VToolbarItems,
  VSpacer,
  VAutocomplete,
  VFooter,
  VSelect,
  VDialog,
  VCard,
  VCardTitle,
  VCardText,
  VCardActions,
  VTabs,
  VTab,
  VTabsItems,
  VTabItem,
  VPagination,
} from 'vuetify/lib';

Vue.use(Vuetify, {
  components: {
    VApp, // required
    VBtn,
    VContainer,
    VContent,
    VFlex,
    VForm,
    VLayout,
    VTextField,
    VTooltip,
    VIcon,
    VToolbar,
    VToolbarTitle,
    VToolbarItems,
    VSpacer,
    VAutocomplete,
    VFooter,
    VSelect,
    VDialog,
    VCard,
    VCardTitle,
    VCardText,
    VCardActions,
    VTabs,
    VTab,
    VTabsItems,
    VTabItem,
    VPagination,
  },
  theme: {
    primary: '#1976d2',
    secondary: '#9D9C9C',
    accent: '#004FFF',
    error: '#FF7070',
  },
  icons: {
    iconfont: 'md',
  },
});
